### ISSUE TITLE
front, back should be protected

### ISSUE THREAD

**Issue by weixing1531** [SCM-NV/ftl#1]
ftlList.F90_template

  `type, public :: CAT(ftlList,FTL_TEMPLATE_TYPE_NAME)

		private

		integer :: psize = 0 

		type(ListNode) :: sentinel 

		FTL_TEMPLATE_TYPE_WRAP, pointer, `protected  :: front => null() 

		FTL_TEMPLATE_TYPE_WRAP, pointer, `protected  :: back => null()`
then the two pointers (front and back) only can be read outside the module (can not be written).

**Comment by robertrueger** [comment]
Unfortunately it is not possible to use the protected keyword in that context. It can only be used to make module variables read-only, but not for members of a type. (If you try the change you proposed, you will also see that compilers won't let you do that, as it is not standard Fortran.)

I am unfortunately not aware of any possibility of making a read-only class member in Fortran. In principle one could of course make front/back a getter method that returns you a pointer, eliminating the possibility of people accidentally modifying the pointers contained in the ftlList. However, if the template type of the ftlList is a derived type, you can then not immediately use the % (member access) on the getter method, like you could do in C++ or Python. You can not do:

mylist%front()%some_member

I thought about making front/back pointer returning functions, but I thought it's too important to have direct access to members of the contained derived type. Therefore I decided for the very convenient, but slightly risky option of just having these public pointers, hoping that people would be wise enough not to modify them ...
