### ISSUE TITLE
intel 2020

### ISSUE THREAD

**Issue by alinelena** [SCM-NV/ftl#6]
https://github.com/SCM-NV/ftl/blob/bcf778bd579c05c8ce1cb27d96e01fcf05591dfa/src/ftlString.F90#L169

this will be defeated by intel 2020...

Alin

**Comment by robertrueger** [comment]
This is a workaround for ifort 18 exclusively. Neither ifort 19, nor 19.1 (from parallel studio 2020) are affected by this issue.
